config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'workouts/arm' => 'workouts#arm'
  get 'workouts/breast' => 'workouts#breast'
  get 'workouts/stomach' => 'workouts#stomach'
  get 'workouts/legs' => 'workouts#legs'
  get 'workouts/diagnosis' => 'workouts#diagnosis'
  resources :workouts
  resources :perfumes
  root 'workouts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
        def index
        end
    
        def new
            @perfume = Perfume.new
        end
    
        def show
            @perfume = Perfume.find_by(id: params[:id])
        end
    
        def create
            perfume = Perfume.new(perfume_params)
            if perfume.save
                flash[:notice] = "診断が完了しました"
                redirect_to perfume_path(perfume.id)
            else
                redirect_to :action => "new"
            end
        end

        private
        def perfume_params
            params.require(:perfume).permit(:question1, :question2, :question3, :question4)
        end    
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    def index
        @workouts = Workout.all
    end

    def new
        @workouts = Workout.new
    end

    def create
        workouts = Workout.new(workout_params)
        if workouts.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    
    def show
        @workouts = Workout.find(params[:id])
    end

    def edit
        @workouts = Workout.find(params[:id])
    end

    def update
        workouts = Workout.find(params[:id])
        if workouts.update(workout_params)
          redirect_to :action => "show", :id => workouts.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        workouts = Workout.find(params[:id])
        workouts.destroy
        redirect_to action: :index
    end

    def diagnosis
      @workouts = Workout.new
    end

    def arm
      @workouts = Workout.all
    end

    def breast
      @workouts = Workout.all
    end

    def stomach
      @workouts = Workout.all
    end

    def legs
      @workouts = Workout.all
    end

  private
    def workout_params
      params.require(:workout).permit(:name, :explain, :number, :time, :youtube_url, :category)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
    def find_youtube_url(youtube_url)
        if youtube_url[0..16] == "https://youtu.be/"
            return youtube_url[17..27]
        else
            return youtube_url[32..42]
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="perfume-container">
        <div class="col-12">
            <h3>Q. 自分がなりたいと思うのは…</h3>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">ゴリマッチョ</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">細マッチョ</label>
            <%= f.radio_button :question1, "3", id: "custom_id3" %>
            <label for="custom_id1">痩せれば何でもいい</label>
        </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
<% end %>

app/views/perfumes/show.html.erb
<div class="perfume-container">
<div class="intoro">
    <h1>診断結果</h1>
</div>
    <% case @perfume.question1 %>
    <% when "1" %>
        <h2>ゴリマッチョへの筋トレ方法</h2>
        <p>ゴリマッチョになるためには自分への追い込みが大切です。</p>
        <p>この人達には以下の筋トレを紹介します。</p>
    <% when "2" %>
        <h2>細マッチョへの筋トレ方法</h2>
        <p>細マッチョになるためには日々の筋トレを継続させることが大切です。</p>
        <p>この人達には以下の筋トレを紹介します。</p>
    <% when "3" %>
        <h2>痩せるための筋トレ方法</h2>
        <p>痩せるためには筋トレも大切ですが、日々の運動と食がも最も大切だと考えます。</p>
        <p>この人達には以下の筋トレを紹介します。</p>
    <% end %>
</div>

app/views/workouts/arm.html.erb
<div class="part-content"
    <h1>arm<h1>
    
</div>

app/views/workouts/breast.html.erb
<div class="part-content"
    <h1>chest</h1>
    
</div>

app/views/workouts/edit.html.erb
<%= form_for @workouts do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %>
    <%= f.text_field :explain, :size => 140 %>
    <%= f.text_field :number, :size => 140 %>
    <%= f.submit "編集する" %>
  <% end %>

app/views/workouts/index.html.erb
<div class="content">
  
  <div class="main-container">
  <header class="header-content">
    <ul class="header-list">
      <%= link_to "診断を始める", new_perfume_path, class: "link" %>
    </ul>
  </header>
  <div class="larger-heading">WORKOUT</div>
    <h3>一覧ページ</h3>
    <%= link_to "arm", workouts_arm_path %>
    <%= link_to "chest", workouts_breast_path %>
    <%= link_to "abdomen", workouts_stomach_path %>
    <%= link_to "legs", workouts_legs_path %>
  </div>

  <div class="word"><h5>鍛えたい部位をクリックしていただくとそれ関連のページに飛ぶことができます。</h5></div>
  
  <div class="body">
    <div class="person">
      <div class="head"></div>
      <a href="workouts/breast"><div class="chest"></div></a>
      <a href="workouts/stomach"><div class="abdomen"></div></a>
      <a href="workouts/arm"><div class="left-arm"></div>
      <div class="right-arm"></div></a>
      <a href="workouts/legs"><div class="left-leg"></div>
      <div class="right-leg"></div></a>
    </div>
  </div>

  <div class="tweets-container">
  <%= link_to "新規投稿へ", new_workout_path %>
    <% @workouts.each do |t| %>
      <div class="tweet">
        <%= t.name %>
        <%= t.explain %>
        <%= t.number %>
        <%= t.time %>
        <%= t.category %>
        <%= link_to "詳細へ", workout_path(t.id) %>
        <%= link_to "編集する", edit_workout_path(t.id) %>
        <%= button_to "削除する", workout_path(t.id), method: :delete %>
      </div>
    <% end %>
  </div>

</div>

app/views/workouts/legs.html.erb
<div class="part-content"
    <h1>legs</h1>
    
</div>

app/views/workouts/new.html.erb
<h1>Workout</h1>
<h3>新規投稿ページ</h3>
<%= form_for @workouts do |f| %>
  <div class="field">
    <%= f.label :トレーニング方法 %>
    <%= f.text_field :name, :size => 40 %>
  </div>

  <div class="field">
    <%= f.label :難易度 %>
    <%= f.select :explain, 
    [["簡単", "簡単"], 
    ["普通", "普通"], 
    ["難しい", "難しい"]], include_blank: "選択して下さい" %>
  </div>

  <divclass="field">
    <%= f.label :回数 %>
    <%= f.select :explain, 
    [["10回", "10回"], 
    ["20回", "20回"], 
    ["30回", "30回"],
    ["40回", "40回"],
    ["50回", "50回"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :セット数 %>
    <%= f.select :explain, 
    [["1セット", "1セット"], 
    ["2セット", "2セット"], 
    ["3セット", "3セット"],
    ["4セット", "4セット"],
    ["5セット", "5セット"]], include_blank: "選択して下さい" %>
  </div>

  <%= f.select :category, [["腕", "arm"], ["胸", "stomach"], ["腹", "stomach"], ["脚", "legs"]], include_blank: "どの投稿？" %>

  <%= f.label :youtube_url %>
      <%= f.text_field :youtube_url, :size => 140 %>

  <%= f.submit "トレーニング方法を投稿する" %>
<% end %>

app/views/workouts/show.html.erb
<h1>Workout</h1>
<h3>Tweet詳細</h3>
<div class="workout">
  <p><%= @workouts.name %></p>
  <p><%= @workouts.explain %></p>
  <p><%= @workouts.number %></p>
  <p><%= @workouts.time %></p>
  <p><%= @workouts.created_at %></p>
  <p><%= @workouts.updated_at %></p>
  <p><%= @workouts.category %></p>
  <p><%= @workouts.youtube_url %></p>
</div>

<%= link_to "Tweet一覧に戻る", workouts_path %>
<%= link_to "編集する", edit_workout_path(@workouts.id) %>

app/views/workouts/stomach.html.erb
<div class="part-content"
    <h1>abdomen</h1>
    
</div>